default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: render_development
  username: nitin
  password: Nitin@11

test:
  <<: *default
  database: render_test
  username: nitin
  password: Nitin@11

production:
  primary: &production_primary
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  
  cable:
    <<: *production_primary
    
  cache:
    <<: *production_primary
    
  queue:
    <<: *production_primary
